---
filebeat_version: 7.10.2

wazuh_template_branch: v4.12.0

filebeat_node_name: node-1

filebeat_output_indexer_hosts:
  # - localhost:9200"
  - 172.31.0.239:9200
  - 172.31.2.225:9200
  - 172.31.13.5:9200  

filebeat_module_package_name: wazuh-filebeat-0.4.tar.gz
filebeat_module_package_path: /tmp/
filebeat_module_destination: /usr/share/filebeat/module
filebeat_module_folder: /usr/share/filebeat/module/wazuh
indexer_security_user: admin
indexer_security_password: changeme
# Security plugin
filebeat_security: true
filebeat_ssl_dir: /etc/pki/filebeat

# Local path to store the generated certificates (Opensearch security plugin)
local_certs_path: "{{ playbook_dir }}/indexer/certificates"
